"""added timestamp to notifications and friend requests and changed updated_at in User to onupdate

Revision ID: b88df682805a
Revises: a5fcf1420811
Create Date: 2025-12-07 16:42:11.738081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88df682805a'
down_revision: Union[str, Sequence[str], None] = 'a5fcf1420811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('friend_requests', 'accepted')
    op.add_column('inbox', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox', 'timestamp')
    op.add_column('friend_requests', sa.Column('accepted', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('friend_requests', 'timestamp')
    # ### end Alembic commands ###
