"""Make curr_location and home_location nullable

Revision ID: fe25b2815709
Revises: 
Create Date: 2025-12-05 15:14:01.853827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe25b2815709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'home_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'curr_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'curr_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'home_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
